# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QYKUg7YAA-5onvG3D9uyUzrFyLK8NPil
"""

n=7
print(n*n)
