# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wfk-DVBzo2TA2JUG1P6mCADilEt5yyGA
"""

a,b=10,20
print(a+b)

